todo/config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  post 'tasks/:id' => 'tasks#update'
  root to: redirect('/tasks')
  get 'pages/:action' => 'pages#:action'

end

todo/app/models/owner.rb
class Owner

  def name
    name = 'Foobar Kadigan'
  end

  def birthdate
    birthdate = Date.new(1990, 12, 22)
  end

  def countdown
    today = Date.today
    birthday = Date.new(today.year, birthdate.month, birthdate.day)
    if birthday > today
    countdown = (birthday - today).to_i
    else
    countdown = (birthday.next_year - today).to_i
    end
  end
end

todo/app/models/task.rb
class Task < ActiveRecord::Base
  validates :name, presence: true
  validates :description, presence: true
end

todo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

todo/app/controllers/pages_controller.rb
class PagesController < ApplicationController

  rescue_from ActionView::MissingTemplate, :with => :invalid_page

  def show
    render params[:id]
  end

  def invalid_page
    redirect_to root_path
  end

end

todo/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
    @greeting = I18n.t ('hello')
  end

  def new
    @current_task = Task.new
  end

  def create
    #render :text => params.inspect
    @url_hash={controller: "tasks", action: "create"}

    @current_task = Task.create params.require("task").permit("name", "description")
    if @current_task.valid?
      redirect_to action: "show", id: @current_task.id
    else
      render action: "new"
    end
  end

  def edit
    @current_task = Task.find_by id: params["id"]
    @url_hash={controller: "tasks", action: "update"}
  end

  def update
    @current_task = Task.find_by id: params["id"]
    @current_task.update params.require("task").permit("name", "description")
    if @current_task.valid?
      redirect_to action: "show", id: @current_task.id
    else
      render action: "new"
    end
  end

  def show
    #render :text => params["id"].inspect
    @current_task = Task.find_by id: params["id"]
  end
end

todo/app/helpers/application_helper.rb
module ApplicationHelper
end

todo/app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

todo/app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav data-topbar>
  <div class="navbar-inverse">
    <div class="navbar-inner">
      <ul class="nav nav-tabs">
        <li ><%= link_to (I18n.t ('application_name')), root_path %></li>
        <li class="<%= 'active' if params[:action] == 'index'%>">
          <%= link_to (I18n.t ('home')), root_path %>
        </li>
        <li class="<%= 'active' if params[:action] == 'new'%>">
          <%= link_to (I18n.t ('new_task_page')), new_task_path %>
        </li>
        <li class="<%= 'active' if params[:controller] == 'pages'%>">
          <%= link_to (I18n.t ('about_page')), '../pages/about' %>
        </li>
      </ul>
    </div>
  </div>

  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

todo/app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

todo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Todo" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Todo" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header class="container-fluid">
      <%= render 'layouts/navigation' %>
    </header>
    <main class="container" role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

todo/app/views/pages/about.html.erb
<h1><%= I18n.t ('about_page')%></h1>
<p class="text-info"><%= I18n.t ('about_description')%></p>

todo/app/views/tasks/_form.html.erb
<%= form_for @current_task, url: @url_hash, html: {:class => "form-task" } do |form| %> 
  <%= I18n.t ('name')%>        :<br> <%= form.text_field :name, :value => @current_task.name || '' %> <br>
  <%= I18n.t ('description')%> :<br> <%= form.text_area :description, size: "24x6", :value => @current_task.description || '' %> <br>
  <%= form.submit (I18n.t ('save')) %>
<% end %>

todo/app/views/tasks/edit.html.erb
<h1><%= I18n.t ('edit_task_page')%></h1>
<p class="text-info"><%= I18n.t ('edit_task_description')%></p>

<%= @current_task.errors.full_messages.to_sentence %>

<%= render partial: 'tasks/form' %>

todo/app/views/tasks/index.html.erb
<h1><%= I18n.t ('index_page')%></h1>
<p class="text-info"><%= @greeting %></p>

<% @tasks.each do |task| %>
	<div>
		<div class="inline lead"><%= link_to task.name, task_path(task)%></div>
		<div class="inline link"><%= link_to (I18n.t ('show')), task_path(task) %></div>		
		<div class="inline link"><%= link_to (I18n.t ('edit')), edit_task_path(task) %></div>		
	</div>
<% end %>
<div class="link"><%= link_to (I18n.t ('new_task_page')), new_task_path %></div>

todo/app/views/tasks/new.html.erb
<h1><%= I18n.t ('new_task_page')%></h1>
<p class="text-info"><%= I18n.t ('new_task_description')%></p>

<%= @current_task.errors.full_messages.to_sentence %>

<%= render partial: 'tasks/form' %>

todo/app/views/tasks/show.html.erb
<h1><%= I18n.t ('show_task_page')%></h1>
<p class="text-info"><%= I18n.t ('show_task_description')%></p>
<div class="lead"><%= @current_task.name %></div>
<div class="text"><%= @current_task.description %></div>
<div class="link"><%= link_to (I18n.t ('edit')), edit_task_path(@current_task) %></div>